insert into asset (assetnum, type, value) values (1, 'S4', 2704);
insert into asset (assetnum, type, value) values (2, 'MDX', 7833);
insert into asset (assetnum, type, value) values (3, 'GT-R', 4383);
insert into asset (assetnum, type, value) values (4, 'Ascender', 6527);
insert into asset (assetnum, type, value) values (5, '600', 2242);
insert into asset (assetnum, type, value) values (6, 'Continental', 1748);
insert into asset (assetnum, type, value) values (7, 'Wrangler', 5853);
insert into asset (assetnum, type, value) values (8, 'Mariner', 6478);
insert into asset (assetnum, type, value) values (9, 'Esteem', 5877);
insert into asset (assetnum, type, value) values (10, 'Brat', 1638);
insert into asset (assetnum, type, value) values (11, 'Colorado', 3930);
insert into asset (assetnum, type, value) values (12, 'Bonneville', 2036);
insert into asset (assetnum, type, value) values (13, 'SVX', 5231);
insert into asset (assetnum, type, value) values (14, 'Rodeo', 3091);
insert into asset (assetnum, type, value) values (15, 'Ram 1500 Club', 4540);
insert into asset (assetnum, type, value) values (16, 'Quattroporte', 2676);
insert into asset (assetnum, type, value) values (17, 'EXP', 3177);
insert into asset (assetnum, type, value) values (18, 'Rodeo', 3886);
insert into asset (assetnum, type, value) values (19, 'Fortwo', 8050);
insert into asset (assetnum, type, value) values (20, '6000', 6632);
insert into asset (assetnum, type, value) values (21, '4Runner', 2474);
insert into asset (assetnum, type, value) values (22, 'Type 2', 2345);
insert into asset (assetnum, type, value) values (23, 'Forester', 2065);
insert into asset (assetnum, type, value) values (24, 'FJ Cruiser', 3900);
insert into asset (assetnum, type, value) values (25, 'A6', 3107);
insert into asset (assetnum, type, value) values (26, 'Civic', 3751);
insert into asset (assetnum, type, value) values (27, 'E-Series', 3210);
insert into asset (assetnum, type, value) values (28, 'Montero Sport', 1588);
insert into asset (assetnum, type, value) values (29, 'Truck', 8451);
insert into asset (assetnum, type, value) values (30, '458 Italia', 4929);
insert into asset (assetnum, type, value) values (31, 'Previa', 5926);
insert into asset (assetnum, type, value) values (32, 'Protege5', 1629);
insert into asset (assetnum, type, value) values (33, 'E350', 5417);
insert into asset (assetnum, type, value) values (34, 'STS', 1314);
insert into asset (assetnum, type, value) values (35, 'TSX', 7312);
insert into asset (assetnum, type, value) values (36, 'Pathfinder', 4505);
insert into asset (assetnum, type, value) values (37, 'Raider', 1304);
insert into asset (assetnum, type, value) values (38, 'E-Series', 7511);
insert into asset (assetnum, type, value) values (39, 'Celica', 9087);
insert into asset (assetnum, type, value) values (40, 'Savana', 6483);
insert into asset (assetnum, type, value) values (41, 'del Sol', 6699);
insert into asset (assetnum, type, value) values (42, 'Nubira', 7399);
insert into asset (assetnum, type, value) values (43, 'D250 Club', 5618);
insert into asset (assetnum, type, value) values (44, 'Lanos', 2609);
insert into asset (assetnum, type, value) values (45, 'Explorer Sport Trac', 4057);
insert into asset (assetnum, type, value) values (46, 'Grand Prix', 8956);
insert into asset (assetnum, type, value) values (47, 'G', 1461);
insert into asset (assetnum, type, value) values (48, '200', 3896);
insert into asset (assetnum, type, value) values (49, 'Grand Vitara', 1491);
insert into asset (assetnum, type, value) values (50, 'Grand Marquis', 9009);
