insert into location (state, city, zip, locationid, type) values ('Florida', 'Saint Petersburg', 18852, 1, 'ATM');
insert into location (state, city, zip, locationid, type) values ('South Dakota', 'Sioux Falls', 35388, 2, 'ATM');
insert into location (state, city, zip, locationid, type) values ('Ohio', 'Toledo', 22248, 3, 'ATM');
insert into location (state, city, zip, locationid, type) values ('California', 'San Diego', 63969, 4, 'ATM');
insert into location (state, city, zip, locationid, type) values ('California', 'San Francisco', 14489, 5, 'ATM');
insert into location (state, city, zip, locationid, type) values ('North Carolina', 'Charlotte', 78143, 6, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Florida', 'Tallahassee', 11774, 7, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Missouri', 'Saint Louis', 40593, 8, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Maryland', 'Silver Spring', 91145, 9, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Florida', 'Fort Lauderdale', 95241, 10, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Ohio', 'Toledo', 97747, 11, 'Teller');
insert into location (state, city, zip, locationid, type) values ('California', 'Sacramento', 29350, 12, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Texas', 'Fort Worth', 56387, 13, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Utah', 'Salt Lake City', 40797, 14, 'Teller');
insert into location (state, city, zip, locationid, type) values ('California', 'San Jose', 13872, 15, 'Teller');
insert into location (state, city, zip, locationid, type) values ('California', 'Ventura', 93605, 16, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Oklahoma', 'Oklahoma City', 66704, 17, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Florida', 'Seminole', 16753, 18, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Pennsylvania', 'Philadelphia', 52898, 19, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Texas', 'El Paso', 30850, 20, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Nevada', 'Las Vegas', 54130, 21, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Texas', 'Houston', 63741, 22, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Texas', 'Dallas', 31126, 23, 'Teller');
insert into location (state, city, zip, locationid, type) values ('New York', 'Syracuse', 42806, 24, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Virginia', 'Richmond', 21784, 25, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Louisiana', 'Baton Rouge', 52599, 26, 'Teller');
insert into location (state, city, zip, locationid, type) values ('New York', 'Flushing', 79902, 27, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Texas', 'Spring', 32532, 28, 'Teller');
insert into location (state, city, zip, locationid, type) values ('North Dakota', 'Fargo', 74867, 29, 'Teller');
insert into location (state, city, zip, locationid, type) values ('Maryland', 'Baltimore', 47565, 30, 'HQ');
